apiVersion: v1
data:
  neurodesk.ardc.edu.au.conf: |
    CVMFS_SERVER_URL="http://cvmfs1.neurodesk.org/cvmfs/@fqrn@;http://cvmfs2.neurodesk.org/cvmfs/@fqrn@;http://cvmfs3.neurodesk.org/cvmfs/@fqrn@"
    CVMFS_PUBLIC_KEY='/etc/cvmfs/config.d/neurodesk.ardc.edu.au.pub'
  neurodesk.ardc.edu.au.pub: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwUPEmxDp217SAtZxaBep
    Bi2TQcLoh5AJ//HSIz68ypjOGFjwExGlHb95Frhu1SpcH5OASbV+jJ60oEBLi3sD
    qA6rGYt9kVi90lWvEjQnhBkPb0uWcp1gNqQAUocybCzHvoiG3fUzAe259CrK09qR
    pX8sZhgK3eHlfx4ycyMiIQeg66AHlgVCJ2fKa6fl1vnh6adJEPULmn6vZnevvUke
    I6U1VcYTKm5dPMrOlY/fGimKlyWvivzVv1laa5TAR2Dt4CfdQncOz+rkXmWjLjkD
    87WMiTgtKybsmMLb2yCGSgLSArlSWhbMA0MaZSzAwE9PJKCCMvTANo5644zc8jBe
    NQIDAQAB
    -----END PUBLIC KEY-----
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: cvmfs
    meta.helm.sh/release-namespace: kubeflow
  name: cvmfs-csi-config-d
  namespace: kubeflow
---
apiVersion: v1
data:
  default.local: |
    CVMFS_USE_GEOAPI=yes
    CVMFS_HTTP_PROXY="DIRECT"

    # It is advised to change these configs in the cache section of the helm values
    # and leave them unchanged here, so they auto-generate.
    CVMFS_QUOTA_LIMIT=5000
    CVMFS_CACHE_BASE=/cvmfs-localcache
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: cvmfs
    meta.helm.sh/release-namespace: kubeflow
  name: cvmfs-csi-default-local
  namespace: kubeflow
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cvmfs
provisioner: cvmfs.csi.cern.ch
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs
  namespace: kubeflow
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      # Volume size value has no effect and is ignored
      # by the driver, but must be non-zero.
      storage: 1
  storageClassName: cvmfs
